name: Build & test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: sudo apt-get install libasound2-dev -y
    - name: Check
      run: cargo check --features "empty"
    - name: Test
      run: cargo test --features "empty"
