name: Build & test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: sudo apt install libasound2-dev
    - name: Test
      run: cargo test --features "empty"
